// Code generated by mockery v2.51.1. DO NOT EDIT.

package git

import (
	mock "github.com/stretchr/testify/mock"
	gitlab "gitlab.com/gitlab-org/api/client-go"
)

// GitlabAPIMock is an autogenerated mock type for the GitlabAPI type
type GitlabAPIMock struct {
	mock.Mock
}

type GitlabAPIMock_Expecter struct {
	mock *mock.Mock
}

func (_m *GitlabAPIMock) EXPECT() *GitlabAPIMock_Expecter {
	return &GitlabAPIMock_Expecter{mock: &_m.Mock}
}

// GetRawFile provides a mock function with given fields: projectID, path, opts
func (_m *GitlabAPIMock) GetRawFile(projectID int, path string, opts *gitlab.GetRawFileOptions) ([]byte, *gitlab.Response, error) {
	ret := _m.Called(projectID, path, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetRawFile")
	}

	var r0 []byte
	var r1 *gitlab.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(int, string, *gitlab.GetRawFileOptions) ([]byte, *gitlab.Response, error)); ok {
		return rf(projectID, path, opts)
	}
	if rf, ok := ret.Get(0).(func(int, string, *gitlab.GetRawFileOptions) []byte); ok {
		r0 = rf(projectID, path, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string, *gitlab.GetRawFileOptions) *gitlab.Response); ok {
		r1 = rf(projectID, path, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(int, string, *gitlab.GetRawFileOptions) error); ok {
		r2 = rf(projectID, path, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GitlabAPIMock_GetRawFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawFile'
type GitlabAPIMock_GetRawFile_Call struct {
	*mock.Call
}

// GetRawFile is a helper method to define mock.On call
//   - projectID int
//   - path string
//   - opts *gitlab.GetRawFileOptions
func (_e *GitlabAPIMock_Expecter) GetRawFile(projectID interface{}, path interface{}, opts interface{}) *GitlabAPIMock_GetRawFile_Call {
	return &GitlabAPIMock_GetRawFile_Call{Call: _e.mock.On("GetRawFile", projectID, path, opts)}
}

func (_c *GitlabAPIMock_GetRawFile_Call) Run(run func(projectID int, path string, opts *gitlab.GetRawFileOptions)) *GitlabAPIMock_GetRawFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(string), args[2].(*gitlab.GetRawFileOptions))
	})
	return _c
}

func (_c *GitlabAPIMock_GetRawFile_Call) Return(_a0 []byte, _a1 *gitlab.Response, _a2 error) *GitlabAPIMock_GetRawFile_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *GitlabAPIMock_GetRawFile_Call) RunAndReturn(run func(int, string, *gitlab.GetRawFileOptions) ([]byte, *gitlab.Response, error)) *GitlabAPIMock_GetRawFile_Call {
	_c.Call.Return(run)
	return _c
}

// ListGroupProjects provides a mock function with given fields: group, opts
func (_m *GitlabAPIMock) ListGroupProjects(group string, opts *gitlab.ListGroupProjectsOptions) ([]*gitlab.Project, *gitlab.Response, error) {
	ret := _m.Called(group, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListGroupProjects")
	}

	var r0 []*gitlab.Project
	var r1 *gitlab.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(string, *gitlab.ListGroupProjectsOptions) ([]*gitlab.Project, *gitlab.Response, error)); ok {
		return rf(group, opts)
	}
	if rf, ok := ret.Get(0).(func(string, *gitlab.ListGroupProjectsOptions) []*gitlab.Project); ok {
		r0 = rf(group, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitlab.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *gitlab.ListGroupProjectsOptions) *gitlab.Response); ok {
		r1 = rf(group, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(string, *gitlab.ListGroupProjectsOptions) error); ok {
		r2 = rf(group, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GitlabAPIMock_ListGroupProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGroupProjects'
type GitlabAPIMock_ListGroupProjects_Call struct {
	*mock.Call
}

// ListGroupProjects is a helper method to define mock.On call
//   - group string
//   - opts *gitlab.ListGroupProjectsOptions
func (_e *GitlabAPIMock_Expecter) ListGroupProjects(group interface{}, opts interface{}) *GitlabAPIMock_ListGroupProjects_Call {
	return &GitlabAPIMock_ListGroupProjects_Call{Call: _e.mock.On("ListGroupProjects", group, opts)}
}

func (_c *GitlabAPIMock_ListGroupProjects_Call) Run(run func(group string, opts *gitlab.ListGroupProjectsOptions)) *GitlabAPIMock_ListGroupProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*gitlab.ListGroupProjectsOptions))
	})
	return _c
}

func (_c *GitlabAPIMock_ListGroupProjects_Call) Return(_a0 []*gitlab.Project, _a1 *gitlab.Response, _a2 error) *GitlabAPIMock_ListGroupProjects_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *GitlabAPIMock_ListGroupProjects_Call) RunAndReturn(run func(string, *gitlab.ListGroupProjectsOptions) ([]*gitlab.Project, *gitlab.Response, error)) *GitlabAPIMock_ListGroupProjects_Call {
	_c.Call.Return(run)
	return _c
}

// ListRepositoryTree provides a mock function with given fields: projectID, opts
func (_m *GitlabAPIMock) ListRepositoryTree(projectID interface{}, opts *gitlab.ListTreeOptions) ([]*gitlab.TreeNode, *gitlab.Response, error) {
	ret := _m.Called(projectID, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListRepositoryTree")
	}

	var r0 []*gitlab.TreeNode
	var r1 *gitlab.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(interface{}, *gitlab.ListTreeOptions) ([]*gitlab.TreeNode, *gitlab.Response, error)); ok {
		return rf(projectID, opts)
	}
	if rf, ok := ret.Get(0).(func(interface{}, *gitlab.ListTreeOptions) []*gitlab.TreeNode); ok {
		r0 = rf(projectID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitlab.TreeNode)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, *gitlab.ListTreeOptions) *gitlab.Response); ok {
		r1 = rf(projectID, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(interface{}, *gitlab.ListTreeOptions) error); ok {
		r2 = rf(projectID, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GitlabAPIMock_ListRepositoryTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRepositoryTree'
type GitlabAPIMock_ListRepositoryTree_Call struct {
	*mock.Call
}

// ListRepositoryTree is a helper method to define mock.On call
//   - projectID interface{}
//   - opts *gitlab.ListTreeOptions
func (_e *GitlabAPIMock_Expecter) ListRepositoryTree(projectID interface{}, opts interface{}) *GitlabAPIMock_ListRepositoryTree_Call {
	return &GitlabAPIMock_ListRepositoryTree_Call{Call: _e.mock.On("ListRepositoryTree", projectID, opts)}
}

func (_c *GitlabAPIMock_ListRepositoryTree_Call) Run(run func(projectID interface{}, opts *gitlab.ListTreeOptions)) *GitlabAPIMock_ListRepositoryTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(*gitlab.ListTreeOptions))
	})
	return _c
}

func (_c *GitlabAPIMock_ListRepositoryTree_Call) Return(_a0 []*gitlab.TreeNode, _a1 *gitlab.Response, _a2 error) *GitlabAPIMock_ListRepositoryTree_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *GitlabAPIMock_ListRepositoryTree_Call) RunAndReturn(run func(interface{}, *gitlab.ListTreeOptions) ([]*gitlab.TreeNode, *gitlab.Response, error)) *GitlabAPIMock_ListRepositoryTree_Call {
	_c.Call.Return(run)
	return _c
}

// SearchProjects provides a mock function with given fields: name, opts
func (_m *GitlabAPIMock) SearchProjects(name string, opts *gitlab.SearchOptions) ([]*gitlab.Project, *gitlab.Response, error) {
	ret := _m.Called(name, opts)

	if len(ret) == 0 {
		panic("no return value specified for SearchProjects")
	}

	var r0 []*gitlab.Project
	var r1 *gitlab.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(string, *gitlab.SearchOptions) ([]*gitlab.Project, *gitlab.Response, error)); ok {
		return rf(name, opts)
	}
	if rf, ok := ret.Get(0).(func(string, *gitlab.SearchOptions) []*gitlab.Project); ok {
		r0 = rf(name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitlab.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *gitlab.SearchOptions) *gitlab.Response); ok {
		r1 = rf(name, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(string, *gitlab.SearchOptions) error); ok {
		r2 = rf(name, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GitlabAPIMock_SearchProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchProjects'
type GitlabAPIMock_SearchProjects_Call struct {
	*mock.Call
}

// SearchProjects is a helper method to define mock.On call
//   - name string
//   - opts *gitlab.SearchOptions
func (_e *GitlabAPIMock_Expecter) SearchProjects(name interface{}, opts interface{}) *GitlabAPIMock_SearchProjects_Call {
	return &GitlabAPIMock_SearchProjects_Call{Call: _e.mock.On("SearchProjects", name, opts)}
}

func (_c *GitlabAPIMock_SearchProjects_Call) Run(run func(name string, opts *gitlab.SearchOptions)) *GitlabAPIMock_SearchProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*gitlab.SearchOptions))
	})
	return _c
}

func (_c *GitlabAPIMock_SearchProjects_Call) Return(_a0 []*gitlab.Project, _a1 *gitlab.Response, _a2 error) *GitlabAPIMock_SearchProjects_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *GitlabAPIMock_SearchProjects_Call) RunAndReturn(run func(string, *gitlab.SearchOptions) ([]*gitlab.Project, *gitlab.Response, error)) *GitlabAPIMock_SearchProjects_Call {
	_c.Call.Return(run)
	return _c
}

// NewGitlabAPIMock creates a new instance of GitlabAPIMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGitlabAPIMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *GitlabAPIMock {
	mock := &GitlabAPIMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
