---
version: 1.64.8

# Options for analysis running.
run:
  # The default concurrency value is the number of available CPU.
  concurrency: 4
  # Exit code when at least one issue was found.
  # Default: 1
  issues-exit-code: 25
  # List of build tags, all linters use it.
  # Default: [].
  build-tags:
    - end2end
    - integration
    - unit

# Output configuration options.
output:
  formats:
    json:
      enabled: true
    text:
      enabled: true
  # Sort results by: filepath, line and column.
  sort-results: true

# All available settings of specific linters.
linters-settings:
  # See the dedicated "linters-settings" documentation section.
  option: value

# Disabled and enabled linters.
linters:
  disable:
    - staticcheck
  enable:
    - asciicheck
    - bodyclose
    - decorder
    - errchkjson
    - errorlint
    - funlen
    - gci
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - gofmt
    - gosec
    - misspell
    - nestif
    - prealloc
    - predeclared
    - revive
    - testifylint
    - unconvert
    - unparam

# Configure detailed linting issues.
issues:
  max-issues-per-linter: 100
  max-same-issues: 10
  exclude:
    - "don't use an underscore in package name"
    - "Log is a global variable"
    - "Validator is a global variable"
    - "type switch on error will fail on wrapped errors. Use errors.As to check for specific errors"
  exclude-dirs:
    - test/mocks
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - gochecknoinits
        - funlen
        - errcheck
        - gochecknoglobals
    - path: '(.+)_mock\.go'
      linters:
        - gochecknoglobals
        - gochecknoinits