// Code generated by mockery v2.51.1. DO NOT EDIT.

package cmd

import (
	scanner "github.com/alican-uelger/deep-scan/internal/scanner"
	mock "github.com/stretchr/testify/mock"
)

// ScannerMock is an autogenerated mock type for the Scanner type
type ScannerMock struct {
	mock.Mock
}

type ScannerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ScannerMock) EXPECT() *ScannerMock_Expecter {
	return &ScannerMock_Expecter{mock: &_m.Mock}
}

// Search provides a mock function with given fields: _a0, _a1
func (_m *ScannerMock) Search(_a0 string, _a1 scanner.SearchOptions) ([]scanner.FileMatch, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []scanner.FileMatch
	var r1 error
	if rf, ok := ret.Get(0).(func(string, scanner.SearchOptions) ([]scanner.FileMatch, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, scanner.SearchOptions) []scanner.FileMatch); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]scanner.FileMatch)
		}
	}

	if rf, ok := ret.Get(1).(func(string, scanner.SearchOptions) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScannerMock_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type ScannerMock_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - _a0 string
//   - _a1 scanner.SearchOptions
func (_e *ScannerMock_Expecter) Search(_a0 interface{}, _a1 interface{}) *ScannerMock_Search_Call {
	return &ScannerMock_Search_Call{Call: _e.mock.On("Search", _a0, _a1)}
}

func (_c *ScannerMock_Search_Call) Run(run func(_a0 string, _a1 scanner.SearchOptions)) *ScannerMock_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(scanner.SearchOptions))
	})
	return _c
}

func (_c *ScannerMock_Search_Call) Return(_a0 []scanner.FileMatch, _a1 error) *ScannerMock_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ScannerMock_Search_Call) RunAndReturn(run func(string, scanner.SearchOptions) ([]scanner.FileMatch, error)) *ScannerMock_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewScannerMock creates a new instance of ScannerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScannerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScannerMock {
	mock := &ScannerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
